export const FETCH_HEADER = "FETCH_HEADER";
export const FETCH_DETAIL = "FETCH_DETAIL";
export const UPDATE_DETAIL = "UPDATE_DETAIL";

export const DIFF_DBYEAR = "DIFF_BDYEAR";

export const CHANGE_SELECTED_HEADER = "CHANGE_SELECTED_HEADER";
export const CHANGE_SELECTED_DETAIL = "CHANGE_SELECTED_DETAIL";
export const CHANGE_CUSTOM_FLAG = "CHANGE_CUSTOM_FLAG";

export const CHANGE_CELL_PREVIEW = "CHANGE_CELL_PREVIEW";

export const CHANGE_TOKEN = "CHANGE_TOKEN";
export const CHANGE_TOOLS = "CHANGE_TOOLS";
export const TOGGLE_TOOL_MODE = "TOGGLE_TOOL_MODE";
export const TOGGLE_TOOL_SHOW = "TOGGLE_TOOL_SHOW";
export const SHOW_LOADPANEL = "SHOW_LOADPANEL";

export const SUBMIT_STATUS = 'SUBMIT_STATUS';
export const REJECT_STATUS = 'REJECT_STATUS';
export const APPROVE_STATUS = 'APPROVE_STATUS';

